force-app/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>The object for storing customized log created from Apex Code</description>
    <label>Application Log</label>
    <nameField>
        <label>Application Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLog__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>The Apex Class name that originated this Application Log</description>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/DebugLevel__c.field-meta.xml
<CustomField>
    <fullName>DebugLevel__c</fullName>
    <description>Debug Level of the Application Log which could be:
Info - logged for additional information
Debug - logged for debug purpose
Warning - logged to capture problem in the system but is not regarded as an error
Error - logged to capture problem in the system but is regarded as an error

The Debug Level is controlled by a custom setting to dictate which Debug Level will be logged.</description>
    <label>Debug Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The target endpoint of a web service log</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <description>The exception message captured by a system exception caught in Apex Code</description>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <description>The originating function in the class (e.g. UpdateDivision() )</description>
    <label>Function</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Custom message for an Application Log</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>The related record id(s)</description>
    <label>Reference Id</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/ReferenceInformation__c.field-meta.xml
<CustomField>
    <fullName>ReferenceInformation__c</fullName>
    <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
    <label>Reference Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/SendEmailAlert__c.field-meta.xml
<CustomField>
    <fullName>SendEmailAlert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this flag is checked, an email alert will be sent to the corresponding recipients according to the Workflow setup.</description>
    <label>Send Email Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Raw exception stack trace for unhandled errors</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLogSetting__c/ApplicationLogSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration for Application Log such as available debug level</description>
    <label>Application Log Setting</label>
</CustomObject>

force-app/main/default/objects/ApplicationLogSetting__c/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Information that is diagnostically helpful to people more than just developers (IT, sysadmins, etc.).</description>
    <inlineHelpText>Information that is diagnostically helpful to people more than just developers (IT, sysadmins, etc.).</inlineHelpText>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApplicationLogSetting__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Any error which is fatal to the operation, but not the service or application (can&#39;t open a required file, missing data, etc.). These errors will force user (administrator, or direct user) intervention. These are usually reserved (in my apps) for incorrect connection strings, missing services, etc.</description>
    <inlineHelpText>Any error which is fatal to the operation, but not the service or application. These errors will force user (administrator, or direct user) intervention. These are usually reserved (in my apps) for incorrect connection strings, missing services, etc.</inlineHelpText>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApplicationLogSetting__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Generally useful information to log (service start/stop, configuration assumptions, etc). Info I want to always have available but usually don&#39;t care about under normal circumstances. This is my out-of-the-box config level.</description>
    <inlineHelpText>Generally useful information to log (service start/stop, configuration assumptions, etc). Info I want to always have available but usually don&#39;t care about under normal circumstances. This is my out-of-the-box config level.</inlineHelpText>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApplicationLogSetting__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Anything that can potentially cause application oddities, but for which I am automatically recovering. (Such as switching from a primary to backup server, retrying an operation, missing secondary data, etc.)</description>
    <inlineHelpText>Anything that can potentially cause application oddities, but for which I am automatically recovering. (Such as switching from a primary to backup server, retrying an operation, missing secondary data, etc.)</inlineHelpText>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ApplicationLoggerTest.cls
@isTest
private class ApplicationLoggerTest {

    @testSetup static void testSetup(){
		ApplicationLogSetting__c appLogSetting = new ApplicationLogSetting__c();
        appLogSetting.Debug__c   = true;
        appLogSetting.Error__c   = true;
        appLogSetting.Info__c    = true;
        appLogSetting.Warning__c = true;

        insert appLogSetting;
	}
    @isTest static void testApplicationLoggerControllerDebug() {
        ApplicationLog__c eachLog = new ApplicationLog__c();
        eachLog.Class__c                  = 'MyClass';
        eachLog.DebugLevel__c             = ApplicationLogger.debugLevel.Debug.name();
        eachLog.Endpoint__c               = 'No Endpoint';
        eachLog.ExceptionMessage__c       = 'No Exception';
        eachLog.Function__c               = 'TestApplicationLog';
        eachLog.Message__c                = 'Test Message';
        eachLog.ReferenceId__c            = 'Reference ID';
        eachLog.ReferenceInformation__c   = 'Reference Information';
        eachLog.SendEmailAlert__c         = false;
        eachLog.StackTrace__c             = 'StackTrace';
        Map<String, String> attachmentMap = new Map<String, String>();
        attachmentMap.put('TestApplicationLog','TestApplicationLog');

        Test.startTest();
        ApplicationLogger.addLogModel(eachLog, attachmentMap);
        Test.stopTest();
    }


    @isTest static void testApplicationLoggerControllerInfo() {
        ApplicationLog__c eachLog = new ApplicationLog__c();
        eachLog.Class__c                  = 'MyClass';
        eachLog.DebugLevel__c             = ApplicationLogger.debugLevel.Info.name();
        eachLog.Endpoint__c               = 'No Endpoint';
        eachLog.ExceptionMessage__c       = 'No Exception';
        eachLog.Function__c               = 'TestApplicationLog';
        eachLog.Message__c                = 'Test Message';
        eachLog.ReferenceId__c            = 'Reference ID';
        eachLog.ReferenceInformation__c   = 'Reference Information';
        eachLog.SendEmailAlert__c         = false;
        eachLog.StackTrace__c             = 'StackTrace';
        Map<String, String> attachmentMap = new Map<String, String>();
        attachmentMap.put('TestApplicationLog','TestApplicationLog');

        Test.startTest();
        ApplicationLogger.addLogModel(eachLog, attachmentMap);
        Test.stopTest();
    }


    @isTest static void testApplicationLoggerControllerError() {
        ApplicationLog__c eachLog = new ApplicationLog__c();
        eachLog.Class__c                  = 'MyClass';
        eachLog.DebugLevel__c             = ApplicationLogger.debugLevel.Error.name();
        eachLog.Endpoint__c               = 'No Endpoint';
        eachLog.ExceptionMessage__c       = 'No Exception';
        eachLog.Function__c               = 'TestApplicationLog';
        eachLog.Message__c                = 'Test Message';
        eachLog.ReferenceId__c            = 'Reference ID';
        eachLog.ReferenceInformation__c   = 'Reference Information';
        eachLog.SendEmailAlert__c         = false;
        eachLog.StackTrace__c             = 'StackTrace';
        Map<String, String> attachmentMap = new Map<String, String>();
        attachmentMap.put('TestApplicationLog','TestApplicationLog');

        Test.startTest();
        ApplicationLogger.addLogModel(eachLog, attachmentMap);
        Test.stopTest();
    }


    @isTest static void testApplicationLoggerControllerWarning() {
        ApplicationLog__c eachLog = new ApplicationLog__c();
        eachLog.Class__c                  = 'MyClass';
        eachLog.DebugLevel__c             = ApplicationLogger.debugLevel.Warning.name();
        eachLog.Endpoint__c               = 'No Endpoint';
        eachLog.ExceptionMessage__c       = 'No Exception';
        eachLog.Function__c               = 'TestApplicationLog';
        eachLog.Message__c                = 'Test Message';
        eachLog.ReferenceId__c            = 'Reference ID';
        eachLog.ReferenceInformation__c   = 'Reference Information';
        eachLog.SendEmailAlert__c         = false;
        eachLog.StackTrace__c             = 'StackTrace';
        Map<String, String> attachmentMap = new Map<String, String>();
        attachmentMap.put('TestApplicationLog','TestApplicationLog');

        Test.startTest();
        ApplicationLogger.addLogModel(eachLog, attachmentMap);
        Test.stopTest();
    }


    @isTest static void testApplicationLoggerControllerInsertModel() {
        ApplicationLog__c eachLog = new ApplicationLog__c();
        eachLog.Class__c                  = 'MyClass';
        eachLog.DebugLevel__c             = ApplicationLogger.debugLevel.Debug.name();
        eachLog.Endpoint__c               = 'No Endpoint';
        eachLog.ExceptionMessage__c       = 'No Exception';
        eachLog.Function__c               = 'TestApplicationLog';
        eachLog.Message__c                = 'Test Message';
        eachLog.ReferenceId__c            = 'Reference ID';
        eachLog.ReferenceInformation__c   = 'Reference Information';
        eachLog.SendEmailAlert__c         = false;
        eachLog.StackTrace__c             = 'StackTrace';
        Map<String, String> attachmentMap = new Map<String, String>();
        attachmentMap.put('TestApplicationLog','TestApplicationLog');

        Test.startTest();
        ApplicationLogger.addLogModel(eachLog, attachmentMap);
        ApplicationLogger.insertLogModel();
        Test.stopTest();
    }
}