force-app/main/default/objects/ApplicationLog__c/ApplicationLog__c.object-meta.xml
<CustomObject>
    <description>The object for storing customized log created from Apex Code</description>
    <label>Application Log</label>
    <nameField>
        <label>Application Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationLog__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>The Apex Class name that originated this Application Log</description>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/DebugLevel__c.field-meta.xml
<CustomField>
    <fullName>DebugLevel__c</fullName>
    <description>Debug Level of the Application Log which could be:
Info - logged for additional information
Debug - logged for debug purpose
Warning - logged to capture problem in the system but is not regarded as an error
Error - logged to capture problem in the system but is regarded as an error

The Debug Level is controlled by a custom setting to dictate which Debug Level will be logged.</description>
    <label>Debug Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <description>The exception message captured by a system exception caught in Apex Code</description>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <description>The originating function in the class (e.g. UpdateDivision() )</description>
    <label>Function</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Custom message for an Application Log</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>The related record id(s)</description>
    <label>Reference Id</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/ReferenceInformation__c.field-meta.xml
<CustomField>
    <fullName>ReferenceInformation__c</fullName>
    <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
    <label>Reference Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Raw exception stack trace for unhandled errors</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationLogSetting__c/ApplicationLogSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration for Application Log such as available debug level</description>
    <label>Application Log Setting</label>
</CustomObject>

force-app/main/default/objects/ApplicationLogSetting__c/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Information that is diagnostically helpful to people more than just developers (IT, sysadmins, etc.).</description>
    <inlineHelpText>Information that is diagnostically helpful to people more than just developers (IT, sysadmins, etc.).</inlineHelpText>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApplicationLogSetting__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Any error which is fatal to the operation, but not the service or application (can&#39;t open a required file, missing data, etc.). These errors will force user (administrator, or direct user) intervention. These are usually reserved (in my apps) for incorrect connection strings, missing services, etc.</description>
    <inlineHelpText>Any error which is fatal to the operation, but not the service or application. These errors will force user (administrator, or direct user) intervention. These are usually reserved (in my apps) for incorrect connection strings, missing services, etc.</inlineHelpText>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApplicationLogSetting__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Generally useful information to log (service start/stop, configuration assumptions, etc). Info I want to always have available but usually don&#39;t care about under normal circumstances. This is my out-of-the-box config level.</description>
    <inlineHelpText>Generally useful information to log (service start/stop, configuration assumptions, etc). Info I want to always have available but usually don&#39;t care about under normal circumstances. This is my out-of-the-box config level.</inlineHelpText>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApplicationLogSetting__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Anything that can potentially cause application oddities, but for which I am automatically recovering. (Such as switching from a primary to backup server, retrying an operation, missing secondary data, etc.)</description>
    <inlineHelpText>Anything that can potentially cause application oddities, but for which I am automatically recovering. (Such as switching from a primary to backup server, retrying an operation, missing secondary data, etc.)</inlineHelpText>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ApplicationLogger.cls
public without sharing class ApplicationLogger {
    private static ApplicationLogger instance;
    public static final String DEFAULT_TOOLONG_PAYLOAD = 'PAYLOAD IS TOO LARGE TO DISPLAY, PLEASE SEE IN ATTACHMENT';
    public enum debugLevel {Debug, Error, Info, Warning}
    public static final String LOG_NAME_PREFIX = 'ALOG-';
    public Map<String, List<Attachment>> attachModelMap = new Map<String, List<Attachment>>();
    public Map<String, ApplicationLog__c> logsModelMap = new Map<String, ApplicationLog__c>();
 
    public ApplicationLogger() {}

    public static ApplicationLogger getInstance() {
        if (instance == null) instance = new ApplicationLogger();
        return instance;
    }
    /*
    *   name   : addLogModel
    *   desc   : to add application log and it's attachment
    *   input  : eachLog       - ApplicationLog (Salesforce Object), 
    *            attachmentMap - Map of Attachment (Key = file name, Value = file content) 
    *            Note: The type of file content is in .txt
    *   output : -
    */
    public static void addLogModel(ApplicationLog__c eachLog, Map<String, String> attachmentMap){

        if(eachLog != null){
            if(isValidInsert(eachLog.DebugLevel__c)){
                DateTime currentDateTime         = Datetime.now();
                String strConvertedDate          = currentDateTime.format('dd-MM-yyyy\'T\'HH:mm:ss:SSS', ''+UserInfo.getTimeZone());
                eachLog.Name                     = LOG_NAME_PREFIX + strConvertedDate;
                eachLog.ExceptionMessage__c	     = getDefaultString(eachLog.ExceptionMessage__c	);
                eachLog.Message__c	             = getDefaultString(eachLog.Message__c);
                eachLog.ReferenceId__c	         = getDefaultString(eachLog.ReferenceId__c);
                eachLog.ReferenceInformation__c	 = getDefaultString(eachLog.ReferenceInformation__c);	                
                eachLog.StackTrace__c	         = getDefaultString(eachLog.StackTrace__c);	
                
                getInstance().logsModelMap.put(eachLog.Name, eachLog);

                if(attachmentMap != null && !attachmentMap.isEmpty()){
                    List<Attachment> attachList = attachmentMap.isEmpty() ? null : createAttachment(attachmentMap, eachLog.Class__c, eachLog.Function__c);
                    getInstance().attachModelMap.put(eachLog.Name, attachList);
                }
            }
        }
    }

    /*
    *   name   : insertLogModel
    *   desc   : insert application log and it's attachment
    *   input  : -
    *   output : -
    */
    public static void insertLogModel(){
        if (!getInstance().logsModelMap.isEmpty()) {
            List<Attachment> attachList = new List<Attachment>();
            insert getInstance().logsModelMap.values();
            for (ApplicationLog__c applog : getInstance().logsModelMap.values()) {
                if (getInstance().attachModelMap.get(applog.Name) != null) {
                    for (Attachment a : getInstance().attachModelMap.get(applog.Name)) {
                        a.ParentId = applog.Id;
                    }
                    attachList.addAll(getInstance().attachModelMap.get(applog.Name));
                }
            }
            Database.SaveResult[] result = Database.insert(attachList, false);
            getInstance().logsModelMap.clear();
            getInstance().attachModelMap.clear();
        }
    }
    
    /*
    *   name   : getDefaultString
    *   desc   : check and return default value if string value is too long
    *   input  : currentValue - Value to check length
    *   output : return value to display
    */
    private static String getDefaultString(String currentValue){
        return (currentValue.length() > 131072) ? DEFAULT_TOOLONG_PAYLOAD : currentValue;
    }

    /*
    *   name   : createAttachment
    *   desc   : to populate attachment of each application log
    *   input  : attachmentMap  - Map of Attachment (Key = file name, Value = file content) 
    *            sourceClass    - Related class of each attachment
    *            sourceFunction - Related function of each attachment
    *   output : Attachment List to Insert
    */
    public static List<Attachment> createAttachment(Map<String, String> attachmentMap, String sourceClass, String sourceFunction){
        List<Attachment> attachList = new List<Attachment>();
        for (String attachName : attachmentMap.keySet()) {
            Attachment attach       = new Attachment();
            attach.Name             = attachName + '_' + sourceClass + ' - ' + sourceFunction + '_' + System.currentTimeMillis();
            attach.Body             = Blob.valueOf(attachmentMap.get(attachName));
            attach.ContentType      = 'Text';
            attachList.add(attach);
        }
        return attachList;
    }

    /*
    *   name   : isValidInsert
    *   desc   : to check that specific debug level is valid to be inserted
    *   input  : debugLevel (String)
    *   output : isThatDebugLevelValidToInsert (Boolean)
    */
    private static Boolean isValidInsert(String eachDebugLevel) {
        Boolean isThatDebugLevelValidToInsert = false;

        ApplicationLogSetting__c orgWidSetting =  ApplicationLogSetting__c.getInstance();
        if (eachDebugLevel == debugLevel.Debug.name() && orgWidSetting.Debug__c) {
            isThatDebugLevelValidToInsert = true;
        }

        if (eachDebugLevel == debugLevel.Error.name()  && orgWidSetting.Error__c) {
            isThatDebugLevelValidToInsert = true;
        }

        if (eachDebugLevel == debugLevel.Info.name()  && orgWidSetting.Info__c) {
            isThatDebugLevelValidToInsert = true;
        }

        if (eachDebugLevel == debugLevel.Warning.name()  && orgWidSetting.Warning__c) {
            isThatDebugLevelValidToInsert = true;
        }
        return isThatDebugLevelValidToInsert;
    }


}